
CREATE TABLE delivery AS
SELECT * FROM restaurant WHERE 1=0;

INSERT INTO delivery (CODE, NAME, TYPECODE)
SELECT CODE, NAME, TYPECODE FROM restaurant;

ALTER TABLE delivery
DROP COLUMN NAME;

ALTER TABLE delivery
DROP COLUMN TYPECODE;

ALTER TABLE delivery
DROP COLUMN hashtag_code;

ALTER TABLE DELIVERY
ADD COLUMN dlvy_avail BOOLEAN;

ALTER TABLE DELIVERY
ADD COLUMN  dlvy_price int;

ALTER TABLE DELIVERY
ADD COLUMN dlvy_ok_price int;

UPDATE DELIVERY
SET DLVY_PRICE = FLOOR(RAND()*10)*1000;

UPDATE DELIVERY
SET DLVY_OK_PRICE = FLOOR(RAND()*10)*1000 + 5000;

UPDATE DELIVERY
SET DLVY_AVAIL = ROUND(RAND());

UPDATE delivery
SET dlvy_price = FLOOR(RAND() * (15 - 8 + 1) + 8) * 1000
WHERE dlvy_price BETWEEN 8000 AND 15000;


UPDATE DELIVERY
SET DLVY_PRICE = NULL, DLVY_OK_PRICE = NULL
WHERE DLVY_AVAIL = 0;
