/* DROP TABLES */
DROP TABLE IF EXISTS Types;
DROP TABLE IF EXISTS Restaurant;
DROP TABLE IF EXISTS Location;
DROP TABLE IF EXISTS Contact;
DROP TABLE IF EXISTS Menu;
DROP TABLE IF EXISTS hashtag;
DROP TABLE IF EXISTS Reservation;
DROP TABLE IF EXISTS Available;
DROP TABLE IF EXISTS BreakTime;
DROP TABLE IF EXISTS Review;
