UPDATE DELIVERY
SET DLVY_PRICE = FLOOR(RAND()*10)*1000;

UPDATE DELIVERY
SET DLVY_OK_PRICE = FLOOR(RAND()*10)*1000 + 5000;

UPDATE DELIVERY
SET DLVY_AVAIL = ROUND(RAND());

UPDATE delivery
SET dlvy_price = FLOOR(RAND() * (15 - 8 + 1) + 8) * 1000
WHERE dlvy_price BETWEEN 8000 AND 15000;


UPDATE DELIVERY
SET DLVY_PRICE = NULL, DLVY_OK_PRICE = NULL
WHERE DLVY_AVAIL = 0;

SELECT *
FROM DELIVERY
WHERE DLVY_AVAIL = 0;

